# Generated by Django 5.2.15 on 2026-07-03 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='نوع الرصيد')),
            ],
            options={
                'verbose_name': 'نوع رصيد',
                'verbose_name_plural': 'أنواع الرصيد',
            },
        ),
        migrations.CreateModel(
            name='ClientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('egp_balance', models.FloatField(default=0, verbose_name='الرصيد المصري')),
                ('lyd_balance', models.FloatField(default=0, verbose_name='الرصيد الليبي')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'رصيد عميل',
                'verbose_name_plural': 'أرصدة العملاء',
            },
        ),
        migrations.CreateModel(
            name='CurrencyCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(max_length=100, verbose_name='نوع العملة')),
            ],
            options={
                'verbose_name': 'نوع عملة',
                'verbose_name_plural': 'أنواع العملات',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='التاريخ')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='المبلغ')),
                ('expense_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوع المصروف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('paid_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='مدفوع بواسطة')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
            },
        ),
        migrations.CreateModel(
            name='FromSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_field', models.CharField(db_column='from', max_length=200, verbose_name='من')),
            ],
            options={
                'verbose_name': 'مصدر',
                'verbose_name_plural': 'المصادر',
            },
        ),
        migrations.CreateModel(
            name='OfficeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=200, verbose_name='اسم المكتب')),
            ],
            options={
                'verbose_name': 'مكتب',
                'verbose_name_plural': 'المكاتب',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=200, verbose_name='نوع الطلب')),
            ],
            options={
                'verbose_name': 'نوع طلب',
                'verbose_name_plural': 'أنواع الطلبات',
            },
        ),
        migrations.CreateModel(
            name='T1Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(blank=True, max_length=200, null=True, verbose_name='الفترة')),
                ('total_in', models.FloatField(blank=True, null=True, verbose_name='إجمالي الوارد')),
                ('total_out', models.FloatField(blank=True, null=True, verbose_name='إجمالي المنصرف')),
                ('exchange_rate', models.FloatField(blank=True, null=True, verbose_name='سعر الصرف')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='الربح')),
                ('profit_rate', models.FloatField(blank=True, null=True, verbose_name='نسبة الربح')),
                ('net_profit_lira', models.FloatField(blank=True, null=True, verbose_name='صافي الربح ليرة')),
                ('net_profit_dollar', models.FloatField(blank=True, null=True, verbose_name='صافي الربح دولار')),
                ('total_lira', models.FloatField(blank=True, null=True, verbose_name='إجمالي ليرة')),
                ('total_dollar', models.FloatField(blank=True, null=True, verbose_name='إجمالي دولار')),
            ],
            options={
                'verbose_name': 'ملخص',
                'verbose_name_plural': 'ملخصات',
            },
        ),
        migrations.CreateModel(
            name='TransferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transfer_type', models.CharField(max_length=200, verbose_name='نوع التحويل')),
            ],
            options={
                'verbose_name': 'نوع تحويل',
                'verbose_name_plural': 'أنواع التحويل',
            },
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_in', models.FloatField(blank=True, null=True, verbose_name='وارد نقدي')),
                ('libyan_cash', models.FloatField(blank=True, null=True, verbose_name='نقدي ليبي')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='التاريخ')),
                ('in_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوع الإيداع')),
                ('exchange_rate', models.FloatField(blank=True, null=True, verbose_name='سعر الصرف')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('balance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.balancetype', verbose_name='نوع الرصيد')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.clientbalance', verbose_name='رصيد من')),
                ('from_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.fromsource', verbose_name='من')),
            ],
            options={
                'verbose_name': 'رصيد',
                'verbose_name_plural': 'الأرصدة',
            },
        ),
        migrations.CreateModel(
            name='Dbcash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfered_amount', models.FloatField(blank=True, null=True, verbose_name='المبلغ المحول')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='التاريخ')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='الوقت')),
                ('order_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الطلب')),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المرسل')),
                ('sender_tele', models.CharField(blank=True, max_length=200, null=True, verbose_name='هاتف المرسل')),
                ('receiver_region', models.CharField(blank=True, max_length=200, null=True, verbose_name='منطقة المستلم')),
                ('transfer_amount', models.FloatField(blank=True, null=True, verbose_name='مبلغ التحويل')),
                ('exchange_rate', models.FloatField(blank=True, null=True, verbose_name='سعر الصرف')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('receiver_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المستلم')),
                ('receiver_tele', models.CharField(blank=True, max_length=200, null=True, verbose_name='هاتف المستلم')),
                ('from_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.fromsource', verbose_name='من')),
                ('office_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.officename', verbose_name='اسم المكتب')),
                ('order_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.ordertype', verbose_name='نوع الطلب')),
                ('transfer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.transfertype', verbose_name='نوع التحويل')),
            ],
            options={
                'verbose_name': 'نقدية',
                'verbose_name_plural': 'النقدية',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfered_amount', models.FloatField(blank=True, null=True, verbose_name='المبلغ المحول')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='التاريخ')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='الوقت')),
                ('order_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الطلب')),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المرسل')),
                ('sender_tele', models.CharField(blank=True, max_length=200, null=True, verbose_name='هاتف المرسل')),
                ('receiver_region', models.CharField(blank=True, max_length=200, null=True, verbose_name='منطقة المستلم')),
                ('transfer_amount', models.FloatField(blank=True, null=True, verbose_name='مبلغ التحويل')),
                ('exchange_rate', models.FloatField(blank=True, null=True, verbose_name='سعر الصرف')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('receiver_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المستلم')),
                ('receiver_tele', models.CharField(blank=True, max_length=200, null=True, verbose_name='هاتف المستلم')),
                ('from_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.fromsource', verbose_name='من')),
                ('office_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.officename', verbose_name='اسم المكتب')),
                ('order_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.ordertype', verbose_name='نوع الطلب')),
                ('transfer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.transfertype', verbose_name='نوع التحويل')),
            ],
            options={
                'verbose_name': 'عملية',
                'verbose_name_plural': 'العمليات',
            },
        ),
    ]
