# Generated by Django 5.2.15 on 2026-07-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officename',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='الكود'),
        ),
    ]
