# Generated by Django 5.2.15 on 2026-07-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_app', '0002_officename_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='database',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
    ]
