# Generated by Django 5.2.15 on 2026-07-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_app', '0003_alter_capital_date_alter_database_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='الوقت'),
        ),
    ]
