# Generated by Django 5.2.15 on 2026-07-03 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_app', '0004_alter_database_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم المنطقة')),
            ],
            options={
                'verbose_name': 'منطقة تسليم',
                'verbose_name_plural': 'مناطق التسليم',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الحوالة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('sender_name', models.CharField(max_length=200, verbose_name='اسم المرسل')),
                ('sender_tele', models.CharField(blank=True, max_length=20, verbose_name='هاتف المرسل')),
                ('sender_notes', models.TextField(blank=True, verbose_name='ملاحظات المرسل')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='اسم المستلم')),
                ('receiver_tele', models.CharField(blank=True, max_length=20, verbose_name='هاتف المستلم')),
                ('receiver_notes', models.TextField(blank=True, verbose_name='ملاحظات المستلم')),
                ('delivery_area_name', models.CharField(blank=True, max_length=200, verbose_name='منطقة التسليم (نص)')),
                ('sent_amount', models.FloatField(default=0, verbose_name='المبلغ المرسل')),
                ('office_commission', models.FloatField(default=0, verbose_name='عمولة المكتب')),
                ('received_amount', models.FloatField(default=0, verbose_name='المبلغ المستلم')),
                ('status', models.CharField(choices=[('pending', 'قيد الإرسال'), ('sent', 'تم الإرسال'), ('received', 'تم الاستلام'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('delivery_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_app.deliveryarea', verbose_name='منطقة التسليم')),
                ('receiver_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_received', to='access_app.officename', verbose_name='مكتب الاستقبال')),
                ('sender_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_sent', to='access_app.officename', verbose_name='مكتب الإرسال')),
            ],
            options={
                'verbose_name': 'حوالة داخلية',
                'verbose_name_plural': 'الحوالات الداخلية',
                'ordering': ['-id'],
            },
        ),
    ]
