# Generated by Django 5.2.15 on 2026-07-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_app', '0005_deliveryarea_internaltransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='اسم المستخدم')),
                ('password', models.CharField(max_length=255, verbose_name='كلمة المرور')),
                ('office_name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم المكتب')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدير النظام')),
                ('perm_home', models.BooleanField(default=True, verbose_name='الرئيسية')),
                ('perm_transactions', models.BooleanField(default=True, verbose_name='عرض الحوالات')),
                ('perm_add_transaction', models.BooleanField(default=True, verbose_name='إضافة حوالة')),
                ('perm_edit_transaction', models.BooleanField(default=True, verbose_name='تعديل حوالة')),
                ('perm_delete_transaction', models.BooleanField(default=False, verbose_name='حذف حوالة')),
                ('perm_capital', models.BooleanField(default=True, verbose_name='عرض الأرصدة')),
                ('perm_add_capital', models.BooleanField(default=True, verbose_name='إضافة رصيد')),
                ('perm_edit_capital', models.BooleanField(default=True, verbose_name='تعديل رصيد')),
                ('perm_delete_capital', models.BooleanField(default=False, verbose_name='حذف رصيد')),
                ('perm_expenses', models.BooleanField(default=True, verbose_name='عرض المصروفات')),
                ('perm_add_expense', models.BooleanField(default=True, verbose_name='إضافة مصروف')),
                ('perm_edit_expense', models.BooleanField(default=True, verbose_name='تعديل مصروف')),
                ('perm_delete_expense', models.BooleanField(default=False, verbose_name='حذف مصروف')),
                ('perm_import_whatsapp', models.BooleanField(default=True, verbose_name='استيراد من واتساب')),
                ('perm_import_balance', models.BooleanField(default=True, verbose_name='استيراد أرصدة')),
                ('perm_internal_transfer', models.BooleanField(default=True, verbose_name='الحوالات الداخلية')),
                ('perm_profits_report', models.BooleanField(default=True, verbose_name='تقرير الأرباح')),
                ('perm_users', models.BooleanField(default=False, verbose_name='إدارة المستخدمين')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
    ]
