# Generated by Django 5.2.15 on 2026-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_app', '0008_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='الحساب مفعل'),
        ),
    ]
