# Generated by Django 5.2.15 on 2026-07-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_app', '0009_systemuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('whatsapp', 'استيراد واتساب'), ('balance', 'استيراد أرصدة')], max_length=20, verbose_name='نوع الاستيراد')),
                ('total_items', models.IntegerField(default=0, verbose_name='إجمالي العناصر')),
                ('success_count', models.IntegerField(default=0, verbose_name='عدد الناجح')),
                ('failed_count', models.IntegerField(default=0, verbose_name='عدد الفاشل')),
                ('failed_details', models.TextField(default='', verbose_name='تفاصيل الفشل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
            ],
            options={
                'verbose_name': 'تنبيه استيراد',
                'verbose_name_plural': 'تنبيهات الاستيراد',
                'ordering': ['-created_at'],
            },
        ),
    ]
