from django.contrib import admin
from django.urls import path
from access_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_view, name='login'),
    path('welcome/', views.welcome_view, name='welcome'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.home, name='home'),
    path('transactions/', views.transactions, name='transactions'),
    path('transactions/delete/<int:id>/', views.delete_transaction, name='delete_transaction'),
    path('transactions/bulk-delete/', views.bulk_delete_transactions, name='bulk_delete_transactions'),
    path('transactions/clear-all/', views.clear_all_transactions, name='clear_transactions'),
    path('capital/', views.capital_list, name='capital_list'),
    path('expenses/', views.expenses_list, name='expenses_list'),
    path('expenses/add/', views.add_expense, name='add_expense'),
    path('expenses/edit/<int:id>/', views.edit_expense, name='edit_expense'),
    path('expenses/delete/<int:id>/', views.delete_expense, name='delete_expense'),
    path('expenses/clear-all/', views.clear_all_expenses, name='clear_expenses'),
    path('transactions/add/', views.add_transaction, name='add_transaction'),
    path('transactions/edit/<int:id>/', views.edit_transaction, name='edit_transaction'),
    path('capital/add/', views.add_capital, name='add_capital'),
    path('capital/edit/<int:id>/', views.edit_capital, name='edit_capital'),
    path('capital/delete/<int:id>/', views.delete_capital, name='delete_capital'),
    path('capital/bulk-delete/', views.bulk_delete_capital, name='bulk_delete_capital'),
    path('capital/clear-all/', views.clear_all_capital, name='clear_capital'),
    path('whatsapp/import/', views.import_whatsapp, name='import_whatsapp'),
    path('whatsapp/export/', views.export_transfers_excel, name='export_transfers'),
    path('whatsapp/import-excel/', views.import_transfers_excel, name='import_transfers_excel'),
    path('capital/import/', views.import_balance, name='import_balance'),
    path('capital/export/', views.export_capital_excel, name='export_capital'),
    path('capital/import-excel/', views.import_capital_excel, name='import_capital_excel'),
    path('api/quick-client/', views.quick_client, name='quick_client'),
    path('api/quick-office/', views.quick_office, name='quick_office'),
    path('transactions/receipt/<int:id>/', views.transaction_receipt, name='transaction_receipt'),
    path('profits/', views.profits_report, name='profits_report'),
    path('carryover/', views.carryover_balance, name='carryover_balance'),
    path('carryover/dismiss/<str:period>/', views.dismiss_carryover, name='dismiss_carryover'),
    path('internal/', views.internal_transfer_list, name='internal_transfer_list'),
    path('internal/add/', views.add_internal_transfer, name='add_internal_transfer'),
    path('internal/success/<int:id>/', views.internal_transfer_success, name='internal_transfer_success'),
    path('internal/receipt/<int:id>/', views.internal_transfer_receipt, name='internal_transfer_receipt'),
    path('internal/bulk-delete/', views.bulk_delete_internal, name='bulk_delete_internal'),
    path('api/quick-area/', views.quick_area, name='quick_area'),
    path('api/internal-status/<int:id>/', views.update_internal_status, name='update_internal_status'),
    path('users/', views.users_list, name='users_list'),
    path('users/add/', views.add_user, name='add_user'),
    path('users/edit/<int:id>/', views.edit_user, name='edit_user'),
    path('users/delete/<int:id>/', views.delete_user, name='delete_user'),
    path('users/toggle-active/<int:id>/', views.toggle_user_active, name='toggle_user_active'),
    path('messages/', views.messages_inbox, name='messages_inbox'),
    path('messages/sent/', views.messages_sent, name='messages_sent'),
    path('messages/compose/', views.message_compose, name='message_compose'),
    path('messages/<int:id>/', views.message_detail, name='message_detail'),
    path('messages/<int:id>/delete/', views.message_delete, name='message_delete'),
    path('api/unread-count/', views.api_unread_count, name='api_unread_count'),
    path('api/new-transfers/', views.api_new_internal_transfers, name='api_new_internal_transfers'),
    path('internal/export/', views.export_internal_excel, name='export_internal_excel'),
    path('internal/import/', views.import_internal_excel, name='import_internal_excel'),
    path('expenses/export/', views.export_expenses_excel, name='export_expenses_excel'),
    path('expenses/import/', views.import_expenses_excel, name='import_expenses_excel'),
    path('api/toggle-maintenance/', views.toggle_maintenance, name='toggle_maintenance'),
    path('import-alerts/', views.import_alerts, name='import_alerts'),
    path('smart-import/', views.smart_import, name='smart_import'),
    path('api/smart-detect/', views.api_smart_detect, name='api_smart_detect'),
    path('api/extension-receive/', views.api_extension_receive, name='api_extension_receive'),
]
